# Setup for PostgreSQL: 
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= Rails.application.credentials.database_password %>
  host: localhost

development:
  <<: *default
  database: myappdb

test:
  <<: *default
  database: myappdb_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] =>
