# Setup for PostgreSQL: 
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= Rails.application.credentials.database_password %>
  host: localhost

development:
  <<: *default
  database: myappdb

test:
  <<: *default
  database: myappdb_test

production:
  <<: *default
  url: <%= ENV["postgresql://rails_blog_app_malachi_db_user:OHZPtBsBUXSDxBoxfn8T6VOunRpBvZvq@dpg-cvr2upngi27c738jql5g-a.singapore-postgres.render.com/rails_blog_app_malachi_db"] =>
  
